apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: guestbook-data
          mountPath: /var/www/html
      volumes:
      - name: guestbook-data
        configMap:
          name: guestbook-data
          items:
            - key: index.html
              path: index.html
              # Add more content files here


