apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app: guestbook
spec:
  selector:
    app: guestbook
  ports:
  - protocol: TCP
    port: 36238 # Change to your desired port
    targetPort: 80
